service: EternalAI

frameworkVersion: "3"

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs14.x
  profile: myawff
  region: us-east-1
  httpApi:
    cors:
      allowedOrigins: ["*"]
      allowedHeaders: ["*"]
    authorizers:
      customAuthorizer:
        type: request
        functionName: AuthorizeUser
        identitySource: $request.header.Authorization
  environment:
    ETERNAL_AI_DB_USERNAME: ${ssm:ETERNAL_AI_DB_USERNAME}
    ETERNAL_AI_DB_PASSWORD: ${ssm:ETERNAL_AI_DB_PASSWORD}
    ETERNAL_AI_DB_ENDPOINT: ${ssm:ETERNAL_AI_DB_ENDPOINT}
    DB_PORT: ${ssm:DEFAULT_DB_PORT}
    ETERNAL_AI_DB_NAME: EternalAiDb
    ACCESS_TOKEN_SECRET: ${ssm:ACCESS_TOKEN_SECRET}
    CHAT_GPT_API_KEY: ${ssm:CHAT_GPT_API_KEY}
    CHAT_GPT_URL: ${ssm:CHAT_GPT_URL}
    STRIPE_SECRET_KEY: ${ssm:STRIPE_SECRET_KEY}
    STRIPE_PRICE_ID: ${ssm:STRIPE_PRICE_ID}
    REFRESH_TOKEN_SECRET: ${ssm:REFRESH_TOKEN_SECRET}

functions: ${file(yml/functions.yml)}
resources: ${file(yml/resources.yml)}
