service: EternalAI

frameworkVersion: "3"

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs14.x
  profile: myawff
  region: us-east-1
  httpApi:
    cors: true
  environment:
    ETERNAL_AI_DB_USERNAME: ${ssm:ETERNAL_AI_DB_USERNAME}
    ETERNAL_AI_DB_PASSWORD: ${ssm:ETERNAL_AI_DB_PASSWORD}
    ETERNAL_AI_DB_ENDPOINT: ${ssm:ETERNAL_AI_DB_ENDPOINT}
    DB_PORT: ${ssm:DEFAULT_DB_PORT}
    ETERNAL_AI_DB_NAME: EternalAiDb
    ACCESS_TOKEN_SECRET: ${ssm:ACCESS_TOKEN_SECRET}

functions: ${file(yml/functions.yml)}
resources: ${file(yml/resources.yml)}
