export type EnvVariables =
  | "ETERNAL_AI_DB_USERNAME"
  | "ETERNAL_AI_DB_PASSWORD"
  | "ETERNAL_AI_DB_ENDPOINT"
  | "DB_PORT"
  | "ETERNAL_AI_DB_NAME"
  | "ACCESS_TOKEN_SECRET"
  | "REGION"
  | "CHAT_GPT_API_KEY"
  | "CHAT_GPT_URL"
  | "STRIPE_SECRET_KEY"
  | "STRIPE_PRICE_ID";
